-- Zombie Genetix — Bulk strain import
-- Run this in Supabase → SQL Editor
-- 119 strains

INSERT INTO strains (breeder, strain, type, sex, thc_cbd, hybrid_type, hybrid_detail, lineage, notes, flower_time, sort_order)
VALUES
  ('Ace Seeds', 'Hokkaido Japan Hemp', 'Photo', 'Reg', '>1% THC', 'Hybrid', 'balanced Hybrid', '2nd Gen pure hemp from Hokkaido Japan', NULL, '6-8 weeks', 1),
  ('Aeque Genetics', 'Cadillac Rainbow', 'Auto', 'Fem', NULL, 'Indica', 'Indica Dom', 'Runtz x Pure Michigan', 'LST for big yields - topping will lead to smaller plants', '75-80 days seed to harvest', 2),
  ('Aeque Genetics', 'Forgotten Road Kill', 'Auto', 'Fem', '24-27% THC', 'Hybrid', '65/35 Indiac', 'Forgotten Skunk x Pure Michigan', 'Larger sized plants - can be topped and LST''d - Doesn''t need a lot of nutes', '75-90 days from seed to harevst', 3),
  ('Aeque Genetics', 'Afgani Cappucino', 'Auto', 'Fem', '23-26% THC', 'Indica', 'Indica Dom', 'Afghan x Pure Michigan', 'Traits from afghan, top/lst after 4th node is ok.', '85-95 days seed to harvest', 4),
  ('Aeque Genetics', 'CB Big D', 'Auto', 'Fem', '0.5% THC / 16% THC', 'Hybrid', '60/40 Ind', 'Pure Love x CBD Diesel', 'Dark Purple almost black - lemon / lime / pepper / orange. 3Gal pot. Light LST.', '75 days seed to harvest', 5),
  ('Atlas Seed Co', 'CBD Warlock', 'Photo', 'Fem', '8% THC / 4% CBD', 'Indica', '90% Indica', 'Warlock X Cannatonic', 'caryophyllene, humulene, myrcene, cis-nerolidol', '7-9 Weeks', 6),
  ('Atlas Seed Co', 'Face Fat', 'Auto', 'Fem', NULL, 'Hybrid', 'Sativa/Indica : 20/80', 'GMO 8 x Fatso', 'F1 cross of backcrossed Fatso and GMO autos', '75 Days', 7),
  ('Atlas Seed Co', 'GMO OG', 'Auto', 'Fem', '20-28% THc', 'Indica', '80% Indica', 'GMO Auto x Mythic OG', NULL, NULL, 8),
  ('Atlas Seed Co', 'Platinum Green Apple Candy', 'Photo', 'Fem', NULL, 'Hybrid', 'balanced Hybrid', 'GAC 211 S1 #1 x Oreoz', NULL, '12-13 weeks', 9),
  ('Atlas Seed Co', 'Wedding Cake', 'Auto', 'Fem', NULL, 'Indica', '80% Indica', 'Wedding Cake Auto x Wedding Cake Auto', NULL, '10-11 Weeks', 10),
  ('Atlas Seed Co', 'White Widow', 'Auto', 'Fem', NULL, 'Hybrid', '50/50', 'White Widow x White Widow Auto', NULL, '65 Days', 11),
  ('Autoflower Breeder''s Club', 'Afghani Caramel Cream', 'Auto', 'Reg', '1:1 THC: CBD', 'Indica', '100% Indica', 'SFV OG Pink Kush is SFV OG x Pink', 'Myrcene, Terpenes May Vary', '8-10 weeks from seed', 12),
  ('Barney''s Farm', 'Runtz', 'Photo', 'Fem', '0.29', 'Sativa', 'Sativa Hybrid', 'Original Z x Gelato', NULL, '55-60 Days (Sept/3rd week)', 13),
  ('Bulk Seeds Guru', 'Gelato', 'Auto', 'Fem', '20% THC', 'Indica', 'Mostly Indica', 'Gelato x Canuk Cookies Auto', 'Freebies from Canuk Seeds (Bulk Seeds)', '8-9 Weeks from seed', 14),
  ('Canuk Seeds', 'Banana Kush', 'Photo', 'Fem', 'THC 23%', 'Indica', 'Mostly Indica', 'Ghost OG x Skunk Haze', NULL, '7-9 Weeks', 15),
  ('Canuk Seeds', 'Banana Punch', 'Photo', 'Fem', 'Up to 26%', 'Indica', 'Mostly Indica', 'Banana OG x Purple Punch', NULL, '8-9 Weeks', 16),
  ('Canuk Seeds', 'CBDurban', 'Photo', 'Fem', '8% thc / 8% cbd', 'Sativa', 'Mostly Sativa', 'IBL Durban Poison', NULL, '60-70', 17),
  ('Canuk Seeds', 'Granddaddy Purple', 'Photo', 'Fem', '25% THC', 'Indica', 'Indica', 'Purple Urkel x Big Bud', NULL, '65-70 days', 18),
  ('Canuk Seeds', 'Mazar', 'Photo', 'Fem', 'Up to 20% THC', 'Indica', 'Indica', 'Skunk #1 x Afghani', NULL, '8-9 Weeks', 19),
  ('Canuk Seeds', 'NYC Diesel', 'Photo', 'Fem', 'Up to 24%', 'Sativa', 'Mostly Sativa', 'Afghani x Mexican Sativa', NULL, '10-12 Weeks', 20),
  ('Canuk Seeds', 'Original Skunk #1', 'Photo', 'Reg', '19% THC', 'Hybrid', 'hybrid', 'Acapulco Gold x Mexican Sativa x Columbian Gold Sativa', NULL, '63 Days', 21),
  ('Canuk Seeds', 'Purpura Uno CBD', 'Photo', 'Reg', '20% CBD / 0.8% THC', 'Hybrid', 'hybrid', 'Viente:Uno CBD x Purple Kush CBD', NULL, '9-10 weeks', 22),
  ('Canuk Seeds', 'Strawberry Banana', 'Photo', 'Fem', 'Up to 32% THC (?)', 'Indica', 'Indica Hybrid', 'Strawberry Bubblegum x Banana Kush', NULL, '9 Weeks', 23),
  ('Canuk Seeds', 'Strawberry Banana Cheese', 'Photo', 'Fem', 'THC 26%', 'Indica', 'Indica Hybrid', 'Strawberry Banana x Cheese', NULL, '8 Weeks', 24),
  ('Crockett Family Farms', 'Hell''s Gold', 'Photo', 'Reg', NULL, 'Hybrid', NULL, '24K x Hells Angels OG', NULL, '60-65 Days', 25),
  ('Crockett Family Farms', 'Kosher Berry', 'Photo', 'Reg', NULL, 'Hybrid', NULL, '(Kosher Kush x Sour) x Strawnana Juice', 'Caryophyllene, myrcene, limonene', '60-65 Days', 26),
  ('Crockett Family Farms', 'Kosher Cheese', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Kosher Kush x Cheese', NULL, '60-65 Days', 27),
  ('Crockett Family Farms', 'Kosher Flame', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Kosher Kush x Hells Angels OG', NULL, '60-65 Days', 28),
  ('Dank Donkey', 'GG''s Cookies', 'Photo', 'Fem', NULL, 'Hybrid', '50/50', 'GG4 x Animal Cookies', NULL, '8 - 9 Weeks', 29),
  ('Dank Donkey', 'Grandi Long Legz', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Grandi Candi x Tagalongz', 'Grandi Candi from ( Grandiflora) and Tagalongz from (3rdcoastgenetics).', NULL, 30),
  ('Dank Donkey', 'Strawberry Frost', 'Photo', 'Reg', NULL, 'Indica', '80% Indica', 'Strawberry Cough x Space Queen', '14-20%', '8-9 Weeks', 31),
  ('Dimebag Seed Co', 'True Spirit', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Grandpa’s Stash R2 (Super Skunk, Afghan Kush, OG Kush) x Hawaiian Peaches (Black Bart’s 80’S Hawaiian x Tom Hill’s North Indian – Tresdawg', 'Old School (pre-cookies) lineages', '56-60 days', 32),
  ('DNA Genetics', 'Challah Cake', 'Photo', 'Fem', NULL, 'Indica', 'Indica dominant hybrid', 'DNA Cake (Gelato Sorbet x Lava Cake) x Challah Bread (Bakers Delight x Kosher Kush)', NULL, '9 Weeks', 33),
  ('Dutch Passion', 'Auto White Widow', 'Auto', 'Fem', 'THC 17%', 'Indica', 'Indica', 'Brazilian and Indian strains', NULL, '75 days', 34),
  ('Ethos Genetics', 'Auto V5', 'Auto', 'Fem', NULL, 'Hybrid', NULL, NULL, NULL, NULL, 35),
  ('Ethos Genetics', 'Tropical Cookies x Grandpa''s Cookies #10', 'Photo', 'Reg', NULL, 'Hybrid', NULL, NULL, 'Could actually be fem auto :)', NULL, 36),
  ('Exotic Genetix', 'Mystic Magic', 'Photo', 'Reg', NULL, 'Hybrid', 'Sat 60%', 'Magic Bullet (CBD) x Stawberries & Cream', 'Use to create CBD Runtz', '50-60 days', 37),
  ('Exotic Genetix', 'Sleezy Rider', 'Photo', 'Fem', NULL, 'Hybrid', 'hybrid', 'Old Dirty Biker x Milk and Cookies', NULL, '8-9 weeks', 38),
  ('FastBuds', 'Cherry Cola Auto', 'Auto', 'Fem', 'THC 28%', 'Hybrid', 'Sativa 45%/Indica 55%', 'Strawberry Pie reverse "Cherry Cola" phenotype, isolation line F3.', NULL, '9-10 Weeks', 39),
  ('FastBuds', 'Cherry Cola Auto RF3', 'Auto', 'Fem', 'THC 31%', 'Hybrid', '45 / 55 Sativa / Indica', 'Cherry Cola Auto F5 all the way down the line (8 Generations)', 'RF3 (F8) - Strawberry Fields x Original blueberry auto', '9-10 Weeks from seed', 40),
  ('FastBuds', 'Gorilla Cookies', 'Auto', 'Fem', 'THC 28%', 'Hybrid', 'Sativa 45%/Indica 55%', 'GG4 Auto F6 x Cookies Auto F5', NULL, '10 Weeks', 41),
  ('FastBuds', 'Gorilla Zkittlez Auto', 'Auto', 'Fem', 'THC 29%', 'Hybrid', '70 / 30 Indica / Sativa', 'GG4 Auto F6 x Z Auto', NULL, '63 Days from seed', 42),
  ('FastBuds', 'LSD-25 F5', 'Auto', 'Fem', 'THC 21%', 'Hybrid', '65 / 35 Indica / Sativa', 'Original Skunk #1 X Auto Purple Kush', 'f5', '9-10 Weeks from seed', 43),
  ('FastBuds', 'Mexican Airlines', 'Auto', 'Fem', 'THC 19%', 'Hybrid', '65 Sativa / 35 Indica', 'Colombian x Mexican', NULL, '10 Weeks', 44),
  ('FastBuds', 'Original Afghan Kush', 'Auto', 'Fem', 'THC 22%', 'Hybrid', 'Sativa 15%/Indica 85%', 'Afghan Auto', NULL, '8-9 Weeks from seed', 45),
  ('FastBuds', 'Original Cheese', 'Auto', 'Fem', 'THC 21%', 'Hybrid', 'Sativa 30%/Indica 70%', 'Cheese Autoflowering', NULL, '9 Weeks', 46),
  ('FastBuds', 'Original Sour Diesel', 'Auto', 'Fem', 'THC 21%', 'Hybrid', 'Sativa 65%/Indica 35%', 'Sour Diesel Cut x FB Auto #1', 'F4', '9-10 Weeks from seed', 47),
  ('FastBuds', 'Tropicana Cookies Auto', 'Auto', 'Fem', 'THC 27%', 'Hybrid', '40 / 60 Sativa / Indica', 'Tropicana Cookies <Oni Seed Co> x Stawberry Banana Auto F5', 'F5', '8-9 Weeks from seed', 48),
  ('Force of Nature Genetics', 'Dante''s Inferno x Super Buff Cherry # 26', 'Photo', 'Fem', NULL, 'Hybrid', NULL, NULL, NULL, '8-9 weeks', 49),
  ('Force of Nature Genetics', 'Pure Michigan (3rd Coast) x Super Buff Cherry #26', 'Photo', 'Fem', NULL, 'Hybrid', NULL, NULL, NULL, '8-9 weeks', 50),
  ('Force of Nature Genetics', 'Super Buff Cherry # 26 S1', 'Photo', 'Fem', NULL, 'Hybrid', NULL, NULL, NULL, '7-8 Weeks', 51),
  ('Force of Nature Genetics', 'Tagalongz #9 X Super Buff Cherry #26', 'Photo', 'Fem', NULL, 'Hybrid', NULL, NULL, NULL, '8-9 weeks', 52),
  ('Guilded Genetics', 'CBD ConLui', 'Photo', 'Fem', NULL, 'Sativa', 'Sativa Dominant Hybrid', 'CBD Terra Italia F1 x Extreme Grandpas Meds F1', NULL, '90 Days', 53),
  ('Hoku Seeds', 'Chones V', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'GTR Seeds: Double Durban THCV (Durban Poision V1 x Auto Durban THCV)', 'THCV-Rich!', NULL, 54),
  ('Hoku Seeds', 'Critical Speed', 'Photo', 'Fem', '1.25:1 thcv:thc', 'Hybrid', NULL, 'Critical Durb #13 x Full Throttle #20', 'Critical Durb: Critical Skunk V F2 x 1:1 Double … and … Full Throttle: Gas Cap x Double Durban 1:1 THCV', NULL, 55),
  ('Hoku Seeds', 'Medi V', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Dinamed (Dinafem) x Double Durban THCV (GTR)', 'Type II Feminized Line CBDV:THCV Rich (Durban Reversal)', '9 Weeks', 56),
  ('Hoku Seeds', 'Mixed Type II Fem Autos', 'Auto', 'Fem', '??', 'Hybrid', '??', 'Mix from all Dr. Chunk and Sour Chunk Auto Series. Sour Chunk: Dr. Chunk Auto x Sour Citron Auto', '??', '??', 57),
  ('Hoku Seeds', 'Sangoma', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'x', 'Type II CBD:CBDV:THC:THCV', '9 Weeks', 58),
  ('Humboldt Seed Co', 'Banana OG', 'Auto', 'Fem', NULL, 'Sativa', 'Sativa Dominant Hybrid', 'Banana OG S1 #21 x Mint Jelly Auto x Banana OG Auto Bx3', 'THC 25%', '80 Days from seed', 59),
  ('Humboldt Seed Co', 'California Sour Diesel', 'Auto', 'Fem', NULL, 'Hybrid', '80 / 20 Sativa / Indica', 'California Sour Diesel x California Sour Diesel Auto x OG Kush Auto', '21% THC', '70 days', 60),
  ('Humboldt Seed Co', 'Caramel Cream', 'Auto', 'Fem', NULL, 'Indica', 'Indica', 'Caramel Cream x Caramel Cream Auto x Sour Apple Auto', '25% THC', '70–90 days seed-to-harvest', 61),
  ('Humboldt Seed Co', 'Emerald Fire OG', 'Auto', 'Fem', NULL, 'Hybrid', '50/50 Hybrid', 'Emerald Fire OG x Fire OG x OG Kush Auto', NULL, '85 Days Seed->Harvest', 62),
  ('Humboldt Seed Co', 'Fortune Cookie', 'Auto', 'Fem', NULL, 'Indica', 'Indica', 'Forum Cut x Caramel Cream', 'THC 22%', '55 Days', 63),
  ('Humboldt Seed Co', 'Garlic Butter', 'Photo', 'Fem', NULL, 'Indica', 'Indica', 'GMO x Fortune Cookie', 'THC 28-32%', '70 Days', 64),
  ('Humboldt Seed Co', 'Pineapple Muffin', 'Auto', 'Fem', 'THC 17-21%', 'Hybrid', 'balanced Hybrid', 'Pineapple Train Wreck x Sour Apple x Blueberry Muffin', NULL, '80-100 Days', 65),
  ('Humboldt Seed Co', 'Squirt Auto', 'Auto', 'Fem', NULL, 'Hybrid', '80 / 20 Sativa / Indica', 'BBM x Tangie x BBM Auto', NULL, '90 days', 66),
  ('In  House Genetics', 'Slurricane #7 S1', 'Photo', 'Fem', NULL, 'Hybrid', 'Hybrid', 'Slurricane #7 x Slurricane #7', 'Self-cross Slurricane #7 phenotype', '60-75', 67),
  ('JAH Seeds', 'God ISS', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'God Bud x Island Sweet Skunk', 'Original God bud from before JOTI lost his genetics.', NULL, 68),
  ('JAH Seeds', 'Sweet Lights', 'Photo', 'Fem', NULL, 'Indica', 'Indica', 'Northern Lights (Peak Seeds BC) x Island Sweet Skunk', NULL, '8-9 Weeks', 69),
  ('JAH Seeds', 'Sleeping Star', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Sensi Star x Crocketts Confidential', 'Low Yielding, Highly Resinous popcorn nugs', NULL, 70),
  ('JAH Seeds', 'Big Mother Skunker', 'Photo', 'Reg', NULL, 'Indica', 'Indica Hybrid', 'Wappa x Island Sweet Skunk', 'High yield, can do a short veg period.', NULL, 71),
  ('JAH Seeds', 'Sweet Bangi 99', 'Photo', 'Fem', NULL, 'Sativa', 'Sativa', 'Island Sweet Skunk x Cinderella 99 IBL) x Bangi Haze F8', 'Purple leaves. Huge colas. Uplifting high. Huge yields.', NULL, 72),
  ('JAH Seeds', 'Burmese Shorty''s Secret', 'Photo', 'Reg', NULL, 'Indica', 'Indica', 'Burmese Shorty x Crocketts Confidential', 'Dark green leaves, wide.', NULL, 73),
  ('JAH Seeds', 'Romulan Rocket', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Blurple Romulan x Island Sweet Skunk', 'Romulan + Blueberry + Island Sweet Skunk - Good yields with even short veg', NULL, 74),
  ('JAH Seeds', 'Sensi Star Purps', 'Photo', 'Reg', NULL, 'Indica', 'Indica Hybrid', 'Sensi Star x The Purps', 'Limited Stretch during Flower!!!', NULL, 75),
  ('JAH Seeds', 'Sweet PCK', 'Photo', 'Fem', NULL, 'Indica', 'Indica Hybrid', 'Pakistani Chitral Kush (Ace Seeds) x Island Sweet Skunk', 'Large Low bottom buds', NULL, 76),
  ('JAH Seeds', 'Dragon''s Tail', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Dutch Dragon x JahBud (90s God Bud x Crocketts Confidential)', 'Dutch Dragon from Paradise seeds.', NULL, 77),
  ('JAH Seeds', 'Sweet Durga', 'Photo', 'Fem', NULL, 'Hybrid', 'Hybrid', 'Durga Mata x Island Sweet Skunk', 'Medicinal ;)', NULL, 78),
  ('JAH Seeds', 'Jahrora borealis', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Northern Lights IBL (PeakSeedsBC) x JahBud (God Bud x Crocketts Confidential)', NULL, NULL, 79),
  ('JAH Seeds', 'Cinderella 99 IBL', 'Photo', 'Reg', NULL, 'Sativa', 'Sativa Dominant Hybrid', 'Bred from bagseed from Jack Herer from the Sensi Smile coffee shop.', 'IBL from peak seeds. Limonene, Caryophyllene, Myrcene', '8-9 Weeks Flower', 80),
  ('JAH Seeds', 'Acid blue', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Acid x Blueberry', 'acid = nyc diesel x <dutch genetics>, likes to be topped, monster cropped.', '65-70 days', 81),
  ('JAH Seeds', 'Blue Widow''s Secret', 'Photo', 'Reg', NULL, 'Hybrid', NULL, '(Jahbud f2 x White Widow) x blueberry', 'Big Buds apparently', NULL, 82),
  ('JAH Seeds', 'Sweet Granddaddy', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Island Sweet Skunk x Granddaddy Purp', NULL, NULL, 83),
  ('JAH Seeds', 'Chitral Cheese BX', 'Photo', 'Fem', NULL, 'Hybrid', NULL, '(Cheese IBL x Pakistani Chitral Kush) x Cheese IBL', NULL, NULL, 84),
  ('JAH Seeds', 'Sensi Starlights BX', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Sensi Star x Northern Lights IBL BX (Back-crossed to the Sensi Star)', NULL, NULL, 85),
  ('JAH Seeds', 'Blue GodISS', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Blueberry x godbud x Island Sweet Skunk', NULL, NULL, 86),
  ('JAH Seeds', 'Blue Hashplant', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Blueberry x hashplant', NULL, NULL, 87),
  ('JAH Seeds', 'Star Hashplant', 'Photo', 'Fem', NULL, 'Indica', 'Indica', 'Sensi Star x HashPlant', 'S1 hashplant from Ace Seeds - Sensi Star from THC Biomed', NULL, 88),
  ('JAH Seeds', 'Shorty''s Special', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Burmese Shorty x Jah Bud f1', NULL, '55-60 Days', 89),
  ('JAH Seeds', 'Blue Cheese', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Blueberry x (Original) Cheese', NULL, NULL, 90),
  ('Kropduster', 'Purple Takato Kush', 'Photo', 'Reg', NULL, 'Hybrid', NULL, 'Landrace - From Taden Khan in Afghanistan', NULL, '10-12 Weeks', 91),
  ('Mephisto Genetics', 'The Wedding Strikes Bear', 'Auto', 'Fem', NULL, 'Hybrid', NULL, 'Mephisto Wedding x ManBearAlienPig', NULL, 'No Data', 92),
  ('Mephisto Genetics', 'Mephisto''s Wedding x 4 Assed Monkey', 'Auto', 'Fem', NULL, 'Hybrid', '60/40 Ind/Sat', '4 Assed Monkey: GG%4 x Grape Crinkle. Mephisto''s Wedding: (Wedding Cake x Double Grape) x Crème de la Chem', 'Freebie - no breeder info re: specific cross.', '65-85 days (no breeder info)', 93),
  ('Mephisto Genetics', 'Jacob''s Remedy', 'Auto', 'Fem', '1:1 THC: CBD', 'Hybrid', '55/45 Ind/Sat', 'Canna Cheese (0THC) x Sour Crack', 'F1 - Hawaiian punch, gassy fuel terps', 'No Data', 94),
  ('Mephisto Genetics', 'CBDank', 'Auto', 'Fem', '1:1 THC: CBD', 'Hybrid', '55/45 Ind/Sat', 'Canna Cheese (0THC) x Mango Runtz', 'F1 - Hawaiian punch, gassy fuel terps', 'No Data', 95),
  ('Multiverse Seeds', 'Crimson Sun', 'Auto', 'Fem', NULL, 'Indica', 'Indica', 'ICC Auto x GSC Auto', NULL, '65-75', 96),
  ('Multiverse Seeds', 'Moonbeam', 'Auto', 'Fem', NULL, 'Indica', '80% Indica', NULL, NULL, '70-ish days', 97),
  ('Multiverse Seeds', 'Blue Dream S1', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Blue Dream x Fatso 84', NULL, '8-10 Weeks', 98),
  ('Multiverse Seeds', 'Gelato 41 S1', 'Photo', 'Fem', '19-25% THC', 'Indica', 'Indica', 'Gelato 41 x Gelato 41', NULL, NULL, 99),
  ('Multiverse Seeds', 'Gorilla Glue S1', 'Photo', 'Fem', '19-25%', 'Hybrid', 'hybrid', 'Gorilla Glue x Gorilla Glue', NULL, NULL, 100),
  ('Multiverse Seeds', 'Green Crack', 'Photo', 'Fem', NULL, 'Sativa', 'Sativa 70%', 'Skunk #1 x Afghani', 'Myrcene, Limonene, Caryophyllene, Linalool, Pinene', '8-10 Weeks', 101),
  ('Multiverse Seeds', 'Mimosa', 'Auto', 'Fem', '19-25%', 'Hybrid', 'hybrid', 'Mimosa Auto x Fatso 84', NULL, '70 days', 102),
  ('Multiverse Seeds', 'Strawberry Cough', 'Photo', 'Fem', '19-25', 'Sativa', 'Sativa', 'Haze x Strawberry Fields', NULL, '8-10 Weeks', 103),
  ('Multiverse Seeds', 'Sunday Driver', 'Photo', 'Fem', '19-25%', 'Hybrid', 'hybrid', 'Fruity Pebbles x Grape Pie', NULL, '8-10 Weeks', 104),
  ('Multiverse Seeds', 'Titan 9', 'Auto', 'Fem', NULL, 'Indica', 'Indica dominant hybrid', 'Cheese auto x Haze Auto', NULL, '60 days', 105),
  ('Native Seed Co', 'Charlotte''s Web', 'Photo', 'Fem', '0.3% THc', 'Hybrid', 'hybrid', 'Not listed - not the best breeder', NULL, '8-9 Weeks', 106),
  ('Oasis Genetics', 'Auto AK47', 'Auto', 'Fem', NULL, 'Sativa', 'Sativa', 'AK x Low Ryder', NULL, '8 Weeks', 107),
  ('QCS', 'Northern Lights', 'Auto', 'Fem', 'THC', 'Indica', 'Indica 90%', NULL, NULL, '8-9 Weeks', 108),
  ('QCS', 'Super Skunk', 'Auto', 'Fem', 'THC', 'Hybrid', NULL, 'Skunk #1 x Afghani', NULL, '60-65 Days', 109),
  ('Reverse Genetics', 'Frozen Cherrycana', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'Frozen Bag x TC#11', 'Frozen Bag: B.A.G.-Michigan Gas Factory Cut x Banana Butter Cups (FEMS)
TC#11: TROPICANA CHERRY #11 x TROPICANA CHERRY #11', '60-65 Days Flower', 110),
  ('Robinhood Seeds', 'Frozen BAG', 'Photo', 'Fem', NULL, 'Hybrid', NULL, 'B.A.G.-Michigan Gas Factory Cut x Banana Butter Cups (FEMS)', 'Gas, Chemical Sour, Funk', '63-65 Days', 111),
  ('Seedsman Seeds', 'Peyote Wi-Fi CBD', 'Photo', 'Fem', '12-14% CBD : 6-8% THC', 'Hybrid', 'hybrid', 'Peyote Purple x Wi-Fi OG x Seedsman CBD #2', NULL, '8-10 Weeks flower', 112),
  ('Self', 'Durban Poison', 'Photo', 'Reg', NULL, 'Sativa', 'Sativa', NULL, 'From my Grow', 'When it''s done.', 113),
  ('Sensi Seeds', 'Skunk Dream CBD', 'Photo', 'Fem', 'THC/CBD - 1:26', 'Hybrid', '70 Sativa / 30 Indica', 'Sensi Skunk x Alpine Delight CBD', NULL, '70-75 Days', 114),
  ('Tastebudz Genetics', 'CRITICAL BANANA SMOOTHIE', 'Photo', 'Fem', NULL, 'Hybrid', '70 Indica / 30 Sativa', 'Banana Punch x Critical', NULL, '8-9 weeks', 115),
  ('The Cali Connection', 'Island Punch', 'Auto', 'Fem', NULL, 'Hybrid', '55 Indica / 45 Sativa', 'Gorilla Glue #4 x Purple Punch Reversed', NULL, '100-112 Days', 116),
  ('The Seed Fair', 'Afghan', 'Auto', 'Fem', 'THC', 'Indica', '90% Indica', 'Afghani Indica X Low Ryder', '~18% THC', '9-10 weeks', 117),
  ('The Seed Fair', 'CBD Kush', 'Auto', 'Fem', '1:2 THC:CBD', 'Hybrid', '60/40 Indica/sativa', 'Kandy Kush', '7%THC 14%CBD', '10-12 weeks', 118),
  ('The Seed Fair', 'Pakistani Chitral Kush', 'Auto', 'Fem', 'THC', 'Indica', '80% Indica', 'Afghan Kush X Pakistani Chitrali', '~12% THC', '50-60 days', 119)
ON CONFLICT DO NOTHING;
